on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  check-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run firmware checker
        run: python3 firmware_checker.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update firmware data"
          file_pattern: "*.db *.xml *.txt"
          commit_user_name: "Github Actions Bot"
          commit_user_email: "actions@github.com"
