name: Purge jsDelivr Cache

on:
  push:
    paths:
      - 'firmware_rss.xml'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr Cache
        run: |
          curl -X GET "https://purge.jsdelivr.net/gh/bearkevin/apple_firmware_checker@main/firmware_rss.xml"

